version: '3.8'
services:
  db:
    image: mariadb:10.5.8
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'for-user-test-only'
      MYSQL_ROOT_PASSWORD: 'for-root-test-only'
    ports:
      - "3306:3306"
    networks:
      - default
networks:
  default:
    name: app-network
